Tag script
nasa-gcn/gcn-schema pull request #101
Opened 2023-06-07 18:07 UTC by dakota002

2023-06-07 18:39 UTC, dakota002 commented
> The CI script needs to actually commit the changes. Also, if the CI script is triggered by tag events, then it's actually running too late: the tagged commit needs to have the version recorded in the JSON files.

Ahh right, converting this to a draft while I work on the update

2023-06-08 15:23 UTC, dakota002 commented
Okay, with this new implementation, whoever is going to do a new version update only has to run a single command:
`npm run update-tags --tag=vX.X.X`

This triggers the following chain of events:
- Parse out tag value from --tag
  - If the tag is missing or doesn't follow the vX.X.X[optional additional content] pattern, exit the process
- Run prettier
- Checks out a new branch `Update-${tag}`, adds all files, commits and pushes 

I am looking into having the PR get created automatically once the branch is pushed

The workflow now only triggers when the PR gets merged. Once merged, the main branch gets tagged to `vX.X.X`, parsed from the PR name

2023-06-08 20:19 UTC, dakota002 commented
Now it generates a PR, cmd line usage is in my previous comment.
On merge of this resulting PR, the main branch gets tagged. 
I think the logic makes sense, but let me know if this is wrong/over-engineered
I also updated the readme to give some guidance on how to use it

2023-06-12 15:55 UTC, lpsinger requested changes
- [ ] Trigger the workflow by changes on the main branch that alter the version number in package.json.
- [ ] The `$id`, `$ref`, and `$schema` fields should be updated on the tagged version, but not on the main branch. You can accomplish this either by updating the version numbers on the main branch, committing and tagging, and changing them back; or by simply changing the version numbers and tagging a dangling commit.

2023-06-12 17:48 UTC, dakota002 commented
> * [ ]  Trigger the workflow by changes on the main branch that alter the version number in package.json.
> * [ ]  The `$id`, `$ref`, and `$schema` fields should be updated on the tagged version, but not on the main branch. You can accomplish this either by updating the version numbers on the main branch, committing and tagging, and changing them back; or by simply changing the version numbers and tagging a dangling commit.

Cool, working on updating it now!

2023-06-22 13:15 UTC, dakota002 commented
I found these after a quick search:
https://github.com/marketplace/actions/detect-and-tag-new-version
https://github.com/marketplace/actions/auto-tag

The first one actually looks like it would handle this case exactly. I can test it out and I'll make an update to this PR if it seems effective

2023-06-23 13:55 UTC, dakota002 commented
@lpsinger I updated the tag script to use the detect and tag new version action. It simplifies our script a lot, but we still have to hook into the version-command input to run the updates on the schema and id fields and get the commit in there that will actually be tagged. Also its important that the commit is run with the -q flag because the version-command takes whatever is output as the tag value. 

I will have another update for the script that actually writes the file paths once nasa-gcn/gcn.nasa.gov/pull/1010 gets merged

2023-06-27 20:49 UTC, lpsinger commented on .github/workflows/tag.yml
> +      - 'package.json'
How about just on push to the main branch?

2023-06-27 21:15 UTC, lpsinger requested changes
- Strictly speaking, we don't want to replace _all_ occurrences of `oldValue` with `newValue` --- only the first one. We have already checked if the key `startsWith` the `oldValue`, so we can construct the new value by slicing and concatenating.
- If we push the tagged schema to the main branch rather than creating a dangling tag, then there will be a lot of large commits with low information content on the main branch. What are the pros and cons of keeping all the commits on the main branch vs. making dangling tags?
- We want _releases_ in addition to tags.

2023-06-27 21:15 UTC, lpsinger commented on gcn/notices/swift/bat/guano/alert.schema.json
> +      "$ref": "/schema/main/gcn/notices/core/AdditionalInfo.schema.json"
Use relative paths for all of these.

2023-06-27 21:15 UTC, lpsinger commented on update-tags.mjs
> +if (!/[0-9]+\.[0-9]+\.[0-9]+.*/.test(version)) {
Why do we need to validate the version number? Why not just take its value verbatim, whatever it is?

2023-06-27 21:15 UTC, lpsinger commented on update-tags.mjs
> +import { execSync } from 'child_process'
You're already using promises. Why not execute external processes asynchronously too?

2023-06-28 16:54 UTC, lpsinger commented on update-tags.mjs
> +if (!/[0-9]+\.[0-9]+\.[0-9]+.*/.test(version)) {
Yeah, just remove it. The version number `0.1` would fail validation, for example.

2023-06-28 17:51 UTC, dakota002 commented
> * Strictly speaking, we don't want to replace _all_ occurrences of `oldValue` with `newValue` --- only the first one. We have already checked if the key `startsWith` the `oldValue`, so we can construct the new value by slicing and concatenating.

The string replace function only should replace the first instance of a match. 
![image](https://github.com/nasa-gcn/gcn-schema/assets/11023698/e6f82b22-a1e7-4707-a717-09979631a6f5)


> * If we push the tagged schema to the main branch rather than creating a dangling tag, then there will be a lot of large commits with low information content on the main branch. What are the pros and cons of keeping all the commits on the main branch vs. making dangling tags?

My concern at first was that the garbage collector thing would remove the dangling commit, but I read that if the commit is tagged, the gc will not remove it. I'm definitely down to implement it this way, is there a best practice or pattern for making the dangling tag? I haven't (intentionally) made use of them before.

> * We want _releases_ in addition to tags.

I'll look for some existing actions that can do this automatically, pretty sure I came across a few in my previous search

2023-06-29 14:25 UTC, lpsinger commented
Would you please make a separate PR with the updates to all of the hardcoded paths in the `.schema.json` and `.json` files? That's just a good idea and I'd like to get that on the main branch immediately, and keep this PR with the tag script small.

2023-06-29 20:43 UTC, dakota002 commented
Yup! https://github.com/nasa-gcn/gcn-schema/pull/103 should do it!

2023-06-30 19:55 UTC, lpsinger commented
Let's try out the following alternative:

- Use [`npm version`](https://docs.npmjs.com/cli/v9/commands/npm-version) for the developer to bump the release on their own system
- `package.json` looks something like this:
```json
{
  "name": "@nasa-gcn/schema",
  "version": "0.0.01",
  "scripts": {
    "version": "node update-version.js && git add -u",
    "postversion": "node update-version.js main && git add -u && git commit -m \"Back to development\""
  }
}
```
- `update-version.js` looks something like this:
```ts
import {version} from 'package.json'

async function updatePaths(ref: string) {
    // Update paths in .json and .schema.json files
}

const [_, ref] = process.argv.slice(2)

await updatePaths(ref || version)
```

2023-07-11 14:54 UTC, closed without merging