Just validation stuff
nasa-gcn/gcn-schema pull request #28
Opened 2023-02-27 21:27 UTC by dakota002

2023-02-27 21:27 UTC, dakota002 commented
The $id fields need to be sorted out, I will make a separate PR if Vidushi hasn't gotten to it already

2023-02-27 21:32 UTC, lpsinger requested changes

2023-02-28 15:27 UTC, lpsinger requested changes

2023-02-28 15:27 UTC, lpsinger commented on validate.mjs
> +  ajv.addSchema(schemas).compile(true)
What happens on error?

Can we please retain the original behavior that:

* if there are no errors, the process exits cleanly
* if there are any validation errors, they are all printed with the format `${path}: ${e.message}`, and then the process exits with status 1
* if there are any errors that are not validation errors, then they are re-thrown

2023-02-28 15:27 UTC, lpsinger commented on validate.mjs
> +  return true
No need for a return value:

```suggestion
```

2023-02-28 16:11 UTC, lpsinger requested changes

2023-02-28 16:11 UTC, lpsinger commented on validate.mjs
> +    )
Move out of the `try` block.

2023-02-28 16:14 UTC, Vidushi-GitHub approved these changes

2023-02-28 16:31 UTC, lpsinger approved these changes

2023-02-28 16:31 UTC, merged